// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCNn9pjL4meC_lktKjPeldJ4Je5OCah0',
    appId: '1:194589000999:web:5539305e10a3c5c389d502',
    messagingSenderId: '194589000999',
    projectId: 'waste-eb978',
    authDomain: 'waste-eb978.firebaseapp.com',
    storageBucket: 'waste-eb978.firebasestorage.app',
    measurementId: 'G-YC9JWLQMCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoGEafyaLL0aLHskjo-PPxaxdwu3jiZM',
    appId: '1:194589000999:android:d8c90449422c292289d502',
    messagingSenderId: '194589000999',
    projectId: 'waste-eb978',
    storageBucket: 'waste-eb978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKdaX4rQCg3IPZH-oUOhia5l7KnDAwk4',
    appId: '1:194589000999:ios:bbc6870404b338b289d502',
    messagingSenderId: '194589000999',
    projectId: 'waste-eb978',
    storageBucket: 'waste-eb978.firebasestorage.app',
    iosBundleId: 'com.example.sampah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNKdaX4rQCg3IPZH-oUOhia5l7KnDAwk4',
    appId: '1:194589000999:ios:bbc6870404b338b289d502',
    messagingSenderId: '194589000999',
    projectId: 'waste-eb978',
    storageBucket: 'waste-eb978.firebasestorage.app',
    iosBundleId: 'com.example.sampah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUCNn9pjL4meC_lktKjPeldJ4Je5OCah0',
    appId: '1:194589000999:web:86859d189a169cb789d502',
    messagingSenderId: '194589000999',
    projectId: 'waste-eb978',
    authDomain: 'waste-eb978.firebaseapp.com',
    storageBucket: 'waste-eb978.firebasestorage.app',
    measurementId: 'G-XG82CTBD5V',
  );
}
